# ----------------------------------------------------------------------------
#
# Package             : numba
# Source Repo         : https://github.com/numba/numba
# Travis Job Link     : https://travis-ci.com/github/asellappen/PyMySQL/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: bonic
arch:
  - amd64
  - ppc64le

python:
  - 3.7


sudo: required
before_install:
  #- sudo apt-get install llvm
  - sudo apt-get install llvm-8*
  - export LLVM_CONFIG=/usr/bin/llvm-config-10
  - ln -s /usr/include/llvm-10/llvm/Config/llvm-config.h config.h
#  - sudo pip install llvmlite==0.35.0
# - pip install "llvmlite==0.35.0"
  - pip install -U llvmlite==0.32.1

install:
  - pip install python-coveralls
  - pip install pytest jinja2 cffi
  - pip install flake8
  - pip install mypy
 # - python setup.py install
  - pip install --no-deps -e .
script:
  #- python -m pytest numba/tests/
  - python -m numba.runtests -l  
  - flake8 numba
  - mypy
  - coverage run runtests.py
