# ----------------------------------------------------------------------------
#
# Package             : numba
# Source Repo         : https://github.com/numba/numba
# Travis Job Link     : https://travis-ci.com/github/asellappen/PyMySQL/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: bionic
arch:
  - amd64
  - ppc64le

python:
  - 3.7
  - 3.8

sudo: required
before_install:
  - sudo apt-get install llvm
  - sudo pip install llvmlite

install:
  - pip install python-coveralls
  - pip install pytest
  - python setup.py install
  - pip install --no-deps -e .
script:
  - python -m pytest numba/tests/
  - python -m pytest numba/testing/
  - coverage run run_coverage.py
  
