# ----------------------------------------------------------------------------
#
# Package             : numba
# Source Repo         : https://github.com/numba/numba
# Travis Job Link     : https://travis-ci.com/github/asellappen/numba/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: focal

arch:
  - amd64
  - ppc64le

python:
  env: PYTHON_VERSION="3.7"
  env: PYTHON_VERSION="3.8"
  
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install python=$PYTHON_VERSION pip  pytest-xdist
  - conda install pytest jinja2 cffi  flake8 mypy numpy
  - pip install python-coveralls --no-cache-dir
  - conda install llvmlite==0.36.0rc1  -c numba

install:
  - pip install --no-deps -e .
jobs:
  include:
    - stage: unit test1
      script: 
      - python -m numba.runtests -j 0,4500,2 -m 
    - stage: unit test2
      script: 
      - python -m numba.runtests -j 1,4500,2 -m
    - stage: unit test3
      script: 
      - python -m numba.runtests -j 4501,9300,2 -m
    - stage: unit test4
      script: 
      - python -m numba.runtests -j 4502,9300,2 -m
    - stage: Other Tests
      script: 
        - flake8 numba
        - mypy
