# ----------------------------------------------------------------------------
#
# Package             : numba
# Source Repo         : https://github.com/numba/numba
# Travis Job Link     : https://travis-ci.com/github/asellappen/PyMySQL/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: focal
arch:
  - amd64
  - ppc64le

python:
  #- 3.7
  - 3.8

sudo: required
before_install:
install:
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install  numpy flake8 pytest
  - conda install -y mypy

install:
  - pip install --no-deps -e .  
  - python setup.py install
script:
  - sh buildscripts/incremental/build.sh
  - sh buildscripts/incremental/test.sh
  - flake8 numba
  - mypy
